# Generated by Django 2.1.1 on 2019-03-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('admission', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('level', models.IntegerField(default=4)),
                ('zealid', models.CharField(max_length=12, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('points', models.IntegerField(default=0)),
                ('freeze', models.BooleanField(default=False)),
                ('lastsub', models.DateTimeField()),
                ('rules', models.BooleanField(default=False)),
                ('poi', models.CharField(default='', max_length=1000)),
                ('tuh', models.CharField(default='', max_length=10000)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-points', 'lastsub'],
            },
        ),
    ]
