# Generated by Django 2.1.1 on 2019-03-03 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='admission',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='poi',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tuh',
        ),
    ]
