# Generated by Django 2.1.1 on 2019-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0002_auto_20190303_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poi',
            field=models.CharField(default='start', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='tuh',
            field=models.CharField(default='start', max_length=10000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
