# Generated by Django 2.1.1 on 2019-03-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0003_auto_20190303_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='poi',
            field=models.TextField(default='start'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tuh',
            field=models.TextField(default='start'),
        ),
    ]
