# Generated by Django 2.1.1 on 2019-03-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitcounter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='hit',
            new_name='no',
        ),
    ]
